_target_: src.datamodules.datamodules.SingleDataModule

defaults:
  - _self_
  - loaders: default.yaml
  - transforms: default.yaml

datasets:
  train:
    _target_: src.datamodules.datasets.ClassificationDataset
    json_path: ${paths.data_dir}/train/data.json

  valid:
    _target_: src.datamodules.datasets.ClassificationDataset
    json_path: ${paths.data_dir}/valid/data.json

  test:
    _target_: src.datamodules.datasets.ClassificationDataset
    json_path: ${paths.data_dir}/test/data.json

  predict:
    dataset1:
      _target_: src.datamodules.datasets.ClassificationDataset
      json_path: ${paths.data_dir}/predict/data1.json
    dataset2:
      _target_: src.datamodules.datasets.ClassificationDataset
      json_path: ${paths.data_dir}/predict/data2.json
